# Generated by Django 3.0.4 on 2020-07-02 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneSaleApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='brand',
            name='idBrand',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='ID must have at least 3 characters')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='idProduct',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Id must have at least 3 characters')]),
        ),
    ]
